# root_dir: "/meerschaum"
# plugins_dir:
  # - "/meerschaum/plugins"
  # - "/app/plugins"

project_name: "m1finance"

sync:
  pipes:
    - connector: "plugin:m1finance"
      metric: "activities"
      columns:
        datetime: "timestamp"
        id: "ticker"

config:
  meerschaum:
    instance: "sql:main"
    connectors:
      sql:
        main: MRSM{meerschaum:connectors:sql:main}

environment: {}
